_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
algorithm:
    value: PPO
environment:
    value: CartPole-v1
total_timesteps:
    value: 50000
